// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcNT54NuncA9Nck-5VQYdbnxwl5pdzsmA',
    appId: '1:272201705683:web:057887a281175671f80c26',
    messagingSenderId: '272201705683',
    projectId: 'event-marketplace-mvp',
    authDomain: 'event-marketplace-mvp.firebaseapp.com',
    storageBucket: 'event-marketplace-mvp.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvOkBwqBwqBwqBwqBwqBwqBwqBwqBwqBw',
    appId: '1:123456789:android:abcdef123456789',
    messagingSenderId: '123456789',
    projectId: 'event-marketplace-app',
    storageBucket: 'event-marketplace-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvOkBwqBwqBwqBwqBwqBwqBwqBwqBwqBw',
    appId: '1:123456789:ios:abcdef123456789',
    messagingSenderId: '123456789',
    projectId: 'event-marketplace-app',
    storageBucket: 'event-marketplace-app.appspot.com',
    iosBundleId: 'com.example.eventMarketplaceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvOkBwqBwqBwqBwqBwqBwqBwqBwqBwqBw',
    appId: '1:123456789:ios:abcdef123456789',
    messagingSenderId: '123456789',
    projectId: 'event-marketplace-app',
    storageBucket: 'event-marketplace-app.appspot.com',
    iosBundleId: 'com.example.eventMarketplaceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvOkBwqBwqBwqBwqBwqBwqBwqBwqBwqBw',
    appId: '1:123456789:web:abcdef123456789',
    messagingSenderId: '123456789',
    projectId: 'event-marketplace-app',
    authDomain: 'event-marketplace-app.firebaseapp.com',
    storageBucket: 'event-marketplace-app.appspot.com',
  );
}
