// Mocks generated by Mockito 5.4.6 from annotations
// in event_marketplace_app/test/integration/auth_navigation_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:io' as _i6;

import 'package:event_marketplace_app/models/user.dart' as _i5;
import 'package:event_marketplace_app/services/auth_service.dart' as _i2;
import 'package:firebase_auth/firebase_auth.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i2.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i4.User?> get authStateChanges => (super.noSuchMethod(
        Invocation.getter(#authStateChanges),
        returnValue: _i3.Stream<_i4.User?>.empty(),
      ) as _i3.Stream<_i4.User?>);

  @override
  _i3.Stream<_i5.AppUser?> get currentUserStream => (super.noSuchMethod(
        Invocation.getter(#currentUserStream),
        returnValue: _i3.Stream<_i5.AppUser?>.empty(),
      ) as _i3.Stream<_i5.AppUser?>);

  @override
  _i3.Future<_i5.AppUser?> getCurrentUser() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUser,
          [],
        ),
        returnValue: _i3.Future<_i5.AppUser?>.value(),
      ) as _i3.Future<_i5.AppUser?>);

  @override
  _i3.Future<_i5.AppUser?> restoreSession() => (super.noSuchMethod(
        Invocation.method(
          #restoreSession,
          [],
        ),
        returnValue: _i3.Future<_i5.AppUser?>.value(),
      ) as _i3.Future<_i5.AppUser?>);

  @override
  _i3.Future<bool> isSessionValid() => (super.noSuchMethod(
        Invocation.method(
          #isSessionValid,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> registerWithEmail({
    required String? name,
    required String? email,
    required String? password,
    required _i5.UserRole? role,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #registerWithEmail,
          [],
          {
            #name: name,
            #email: email,
            #password: password,
            #role: role,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i5.AppUser?> signUpWithEmailAndPassword({
    required String? email,
    required String? password,
    required String? displayName,
    required _i5.UserRole? role,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUpWithEmailAndPassword,
          [],
          {
            #email: email,
            #password: password,
            #displayName: displayName,
            #role: role,
          },
        ),
        returnValue: _i3.Future<_i5.AppUser?>.value(),
      ) as _i3.Future<_i5.AppUser?>);

  @override
  _i3.Future<_i5.AppUser?> signInWithEmailAndPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithEmailAndPassword,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i3.Future<_i5.AppUser?>.value(),
      ) as _i3.Future<_i5.AppUser?>);

  @override
  _i3.Future<_i5.AppUser?> signInAsGuest() => (super.noSuchMethod(
        Invocation.method(
          #signInAsGuest,
          [],
        ),
        returnValue: _i3.Future<_i5.AppUser?>.value(),
      ) as _i3.Future<_i5.AppUser?>);

  @override
  _i3.Future<_i5.AppUser?> signInWithGoogle() => (super.noSuchMethod(
        Invocation.method(
          #signInWithGoogle,
          [],
        ),
        returnValue: _i3.Future<_i5.AppUser?>.value(),
      ) as _i3.Future<_i5.AppUser?>);

  @override
  _i3.Future<_i5.AppUser?> signInWithGoogleWeb() => (super.noSuchMethod(
        Invocation.method(
          #signInWithGoogleWeb,
          [],
        ),
        returnValue: _i3.Future<_i5.AppUser?>.value(),
      ) as _i3.Future<_i5.AppUser?>);

  @override
  _i3.Future<_i5.AppUser?> handleGoogleRedirectResult() => (super.noSuchMethod(
        Invocation.method(
          #handleGoogleRedirectResult,
          [],
        ),
        returnValue: _i3.Future<_i5.AppUser?>.value(),
      ) as _i3.Future<_i5.AppUser?>);

  @override
  _i3.Future<_i5.AppUser?> signInWithVK(
          {_i5.UserRole? role = _i5.UserRole.customer}) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithVK,
          [],
          {#role: role},
        ),
        returnValue: _i3.Future<_i5.AppUser?>.value(),
      ) as _i3.Future<_i5.AppUser?>);

  @override
  _i3.Future<_i5.AppUser?> handleVkCallback(String? code) =>
      (super.noSuchMethod(
        Invocation.method(
          #handleVkCallback,
          [code],
        ),
        returnValue: _i3.Future<_i5.AppUser?>.value(),
      ) as _i3.Future<_i5.AppUser?>);

  @override
  _i3.Future<void> resetPassword(String? email) => (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [email],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateUserProfile({
    String? displayName,
    String? photoURL,
    _i5.UserRole? role,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserProfile,
          [],
          {
            #displayName: displayName,
            #photoURL: photoURL,
            #role: role,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateUserProfileWithImage({
    String? displayName,
    _i6.File? imageFile,
    _i5.UserRole? role,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserProfileWithImage,
          [],
          {
            #displayName: displayName,
            #imageFile: imageFile,
            #role: role,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteAccount() => (super.noSuchMethod(
        Invocation.method(
          #deleteAccount,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> signOutFromAll() => (super.noSuchMethod(
        Invocation.method(
          #signOutFromAll,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
