name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        channel: 'stable'
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Build Web
      run: flutter build web --release
      
    - name: Build Android APK
      run: flutter build apk --release
      
    - name: Build Windows
      run: flutter build windows --release
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build/web/
          build/app/outputs/flutter-apk/app-release.apk
          build/windows/x64/runner/Release/
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}